volumes:
  postgres_data_sp1:

services:
  db:
    container_name: postgres_db_sp1
    image: postgres:17.5-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data_sp1:/var/lib/postgresql/data
